# Generated by Django 5.0 on 2026-01-26 02:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agregado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Agregado",
                "verbose_name_plural": "Agregados",
                "db_table": "agregado",
            },
        ),
        migrations.CreateModel(
            name="RangoPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="Código"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                (
                    "yarda_minima",
                    models.DecimalField(
                        decimal_places=1, max_digits=10, verbose_name="Yarda Mínima"
                    ),
                ),
                (
                    "yarda_maxima",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=10,
                        null=True,
                        verbose_name="Yarda Máxima",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rango de Pedido",
                "verbose_name_plural": "Rangos de Pedido",
                "db_table": "rango_pedido",
            },
        ),
        migrations.CreateModel(
            name="AgregadoPrecio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                (
                    "motivo_cambio",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Motivo Cambio"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "agregado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="precios",
                        to="administracion.agregado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio de Agregado",
                "verbose_name_plural": "Precios de Agregados",
                "db_table": "agregado_precio",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="PrecioRangoPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.IntegerField(
                        blank=True, null=True, unique=True, verbose_name="Código"
                    ),
                ),
                (
                    "precio_por_yarda",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio por Yarda"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                (
                    "motivo_cambio",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Motivo Cambio"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "rango_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="precios",
                        to="administracion.rangopedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio por Rango de Pedido",
                "verbose_name_plural": "Precios por Rango de Pedido",
                "db_table": "precio_rango_pedido",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
