# Generated by Django 5.0 on 2026-02-10 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoconcreto',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='TipoConcretoPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('motivo_cambio', models.CharField(blank=True, max_length=255, verbose_name='Motivo Cambio')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('tipo_concreto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.tipoconcreto')),
            ],
            options={
                'verbose_name': 'Tipo de concreto precio',
                'verbose_name_plural': 'Tipos de concretos precios',
                'db_table': 'administracion"."tipo_concreto_precio',
                'managed': True,
            },
        ),
    ]
