# Generated by Django 5.0 on 2026-02-12 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipoconcretoprecio",
            name="fecha_inicio",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Fecha Inicio"
            ),
        ),
    ]
