# Generated by Django 5.0 on 2026-02-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preciohultdelivery",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
    ]
