# Generated by Django 5.0 on 2026-02-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0002_agregadoprecio_codigo_preciohultdelivery_codigo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agregadoprecio",
            name="fecha_actualizacion",
        ),
        migrations.RemoveField(
            model_name="preciohultdelivery",
            name="fecha_actualizacion",
        ),
        migrations.RemoveField(
            model_name="tipoconcretoprecio",
            name="fecha_actualizacion",
        ),
        migrations.AddField(
            model_name="agregadoprecio",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha Modificación"
            ),
        ),
        migrations.AddField(
            model_name="preciohultdelivery",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha Modificación"
            ),
        ),
        migrations.AddField(
            model_name="tipoconcretoprecio",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha Modificación"
            ),
        ),
    ]
