# Generated by Django 5.0 on 2026-02-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_tipoconcreto_nombre_tipoconcretoprecio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoconcretoprecio',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='tipoconcretoprecio',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
