# Generated by Django 5.0 on 2026-02-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0003_remove_agregadoprecio_fecha_actualizacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agregado",
            name="fecha_actualizacion",
        ),
        migrations.RemoveField(
            model_name="hultdelivery",
            name="fecha_actualizacion",
        ),
        migrations.RemoveField(
            model_name="tipoconcreto",
            name="fecha_actualizacion",
        ),
        migrations.AddField(
            model_name="agregado",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha Modificación"
            ),
        ),
        migrations.AddField(
            model_name="hultdelivery",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha Modificación"
            ),
        ),
        migrations.AddField(
            model_name="tipoconcreto",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha Modificación"
            ),
        ),
    ]
