# Generated by Django 5.0 on 2026-02-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_remove_tipoconcretoprecio_is_delete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciohultdelivery',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='preciohultdelivery',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
