# Generated by Django 6.0.2 on 2026-02-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0004_remove_agregado_fecha_actualizacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hultdelivery",
            name="codigo",
            field=models.CharField(
                default=1, max_length=20, unique=True, verbose_name="Código"
            ),
            preserve_default=False,
        ),
    ]
