# Generated by Django 6.0.2 on 2026-02-15 18:09

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0005_hultdelivery_codigo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalAgregado",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Agregado",
                "verbose_name_plural": "historical Agregados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAgregadoPrecio",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Código"
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "motivo_cambio",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Motivo Cambio"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "agregado",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="administracion.agregado",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Precio de Agregado",
                "verbose_name_plural": "historical Precios de Agregados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalHultDelivery",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Código"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Nombre"
                    ),
                ),
                (
                    "yarda_minima",
                    models.DecimalField(
                        decimal_places=1, max_digits=10, verbose_name="Yarda Mínima"
                    ),
                ),
                (
                    "yarda_maxima",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=10,
                        null=True,
                        verbose_name="Yarda Máxima",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Hult Delivery",
                "verbose_name_plural": "historical Hults Deliverys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPrecioHultDelivery",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Código"
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "motivo_cambio",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Motivo Cambio"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hult_delivery",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="administracion.hultdelivery",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Precio por Hult Delivery",
                "verbose_name_plural": "historical Precios por Hult Delivery",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTipoConcreto",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Código"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nombre"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tipo Concreto",
                "verbose_name_plural": "historical Tipos de Concretos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTipoConcretoPrecio",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Código"
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "motivo_cambio",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Motivo Cambio"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_concreto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="administracion.tipoconcreto",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tipo de concreto precio",
                "verbose_name_plural": "historical Tipos de concretos precios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
