# Generated by Django 5.0 on 2026-01-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Usuario"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Correo"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("SSN", "SSN"), ("ITIN", "ITIN")],
                        max_length=4,
                        verbose_name="Tipo de documento",
                    ),
                ),
                ("numero", models.IntegerField(verbose_name="Número")),
                (
                    "nombre_apellido",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nom/Ape"
                    ),
                ),
                (
                    "pregunta_01",
                    models.CharField(
                        default="INDETERMINADA", max_length=255, verbose_name="Preg. 01"
                    ),
                ),
                (
                    "pregunta_02",
                    models.CharField(
                        default="INDETERMINADA", max_length=255, verbose_name="Preg. 02"
                    ),
                ),
                (
                    "pregunta_03",
                    models.CharField(
                        default="INDETERMINADA", max_length=255, verbose_name="Preg. 03"
                    ),
                ),
                (
                    "respuesta_01",
                    models.CharField(
                        default="INDETERMINADA", max_length=255, verbose_name="Resp. 01"
                    ),
                ),
                (
                    "respuesta_02",
                    models.CharField(
                        default="INDETERMINADA", max_length=255, verbose_name="Resp. 02"
                    ),
                ),
                (
                    "respuesta_03",
                    models.CharField(
                        default="INDETERMINADA", max_length=255, verbose_name="Resp. 03"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Registro"
                    ),
                ),
                (
                    "is_customer",
                    models.BooleanField(default=False, verbose_name="Es Cliente"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=True, verbose_name="VERIFICADO"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Esta Activo"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="Personal de Confianza"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="Es ROOT"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": 'cuenta"."usuario',
                "managed": True,
                "unique_together": {("tipo_documento", "numero")},
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cuenta.user",),
        ),
    ]
