# Generated by Django 6.0.2 on 2026-02-15 18:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuenta", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Usuario"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=255, verbose_name="Correo"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("SSN", "SSN"), ("ITIN", "ITIN")],
                        max_length=4,
                        verbose_name="Tipo de documento",
                    ),
                ),
                ("numero", models.IntegerField(verbose_name="Número")),
                (
                    "nombre_apellido",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nom/Ape"
                    ),
                ),
                (
                    "pregunta_01",
                    models.CharField(
                        default="INDETERMINADA", max_length=255, verbose_name="Preg. 01"
                    ),
                ),
                (
                    "pregunta_02",
                    models.CharField(
                        default="INDETERMINADA", max_length=255, verbose_name="Preg. 02"
                    ),
                ),
                (
                    "pregunta_03",
                    models.CharField(
                        default="INDETERMINADA", max_length=255, verbose_name="Preg. 03"
                    ),
                ),
                (
                    "respuesta_01",
                    models.CharField(
                        default="INDETERMINADA", max_length=255, verbose_name="Resp. 01"
                    ),
                ),
                (
                    "respuesta_02",
                    models.CharField(
                        default="INDETERMINADA", max_length=255, verbose_name="Resp. 02"
                    ),
                ),
                (
                    "respuesta_03",
                    models.CharField(
                        default="INDETERMINADA", max_length=255, verbose_name="Resp. 03"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Registro"
                    ),
                ),
                (
                    "is_customer",
                    models.BooleanField(default=False, verbose_name="Es Cliente"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=True, verbose_name="VERIFICADO"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Esta Activo"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="Personal de Confianza"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="Es ROOT"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Usuario",
                "verbose_name_plural": "historical Usuarios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
