# Generated by Django 5.0 on 2026-01-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuenta", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cuenta.user",),
        ),
        migrations.AddField(
            model_name="user",
            name="is_customer",
            field=models.BooleanField(default=False, verbose_name="Es Cliente"),
        ),
    ]
