# Generated by Django 5.0 on 2025-12-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuenta", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tipo_documento",
            field=models.CharField(
                choices=[("SSN", "SSN"), ("ITIN", "ITIN")],
                max_length=4,
                verbose_name="Tipo de documento",
            ),
        ),
    ]
