# Generated by Django 5.0 on 2026-01-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EstadoConductor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Descripción"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Es Eliminado"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado Conductor",
                "verbose_name_plural": "Estados Conductores",
                "db_table": "estado_conductor",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="EstadoPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Descripción"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Es Eliminado"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado Pedido",
                "verbose_name_plural": "Estados Pedidos",
                "db_table": "estado_pedido",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="EstadoVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                (
                    "descripcion",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Descripción"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Es Eliminado"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado Vehículo",
                "verbose_name_plural": "Estados Vehículos",
                "db_table": "estado_vehiculo",
                "managed": True,
            },
        ),
    ]
