# Generated by Django 5.0 on 2026-02-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auxiliares", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estadoconductor",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
        migrations.AlterField(
            model_name="estadopedido",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
        migrations.AlterField(
            model_name="estadovehiculo",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
    ]
