# Generated by Django 5.0 on 2026-01-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auxiliares", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estadoconductor",
            name="estatus",
        ),
        migrations.RemoveField(
            model_name="estadopedido",
            name="estatus",
        ),
        migrations.RemoveField(
            model_name="estadovehiculo",
            name="estatus",
        ),
        migrations.AddField(
            model_name="estadoconductor",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Es Eliminado"),
        ),
        migrations.AddField(
            model_name="estadopedido",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Es Eliminado"),
        ),
        migrations.AddField(
            model_name="estadovehiculo",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Es Eliminado"),
        ),
    ]
