# Generated by Django 5.0 on 2026-02-13 21:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administracion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_comercial",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "db_table": 'proveedores"."proveedor',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProveedorAgregadoPrecio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "agregado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="administracion.agregado",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proveedores.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio de Agregado",
                "verbose_name_plural": "Precios de Agregados",
                "db_table": 'proveedores"."agregado_precio',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProveedorTipoConcretoPrecio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Actualización"
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proveedores.proveedor",
                    ),
                ),
                (
                    "tipo_concreto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="administracion.tipoconcreto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio de Tipo Concreto",
                "verbose_name_plural": "Precios de Tipos de Concretos",
                "db_table": 'proveedores"."tipo_concreto_precio',
                "managed": True,
            },
        ),
    ]
