# Generated by Django 5.0 on 2026-02-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedoragregadoprecio",
            name="codigo",
            field=models.CharField(
                default=1, max_length=20, unique=True, verbose_name="Código"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proveedortipoconcretoprecio",
            name="codigo",
            field=models.CharField(
                default=1, max_length=20, unique=True, verbose_name="Código"
            ),
            preserve_default=False,
        ),
    ]
