# Generated by Django 5.0 on 2026-02-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0002_proveedoragregadoprecio_codigo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proveedoragregadoprecio",
            old_name="codigo",
            new_name="codigo_precio",
        ),
        migrations.RenameField(
            model_name="proveedortipoconcretoprecio",
            old_name="codigo",
            new_name="codigo_precio",
        ),
    ]
