# Generated by Django 5.0 on 2026-02-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "proveedores",
            "0003_rename_codigo_proveedoragregadoprecio_codigo_precio_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="proveedoragregadoprecio",
            old_name="codigo_precio",
            new_name="codigo",
        ),
        migrations.RenameField(
            model_name="proveedortipoconcretoprecio",
            old_name="codigo_precio",
            new_name="codigo",
        ),
    ]
