# Generated by Django 5.0 on 2026-02-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0002_agregadoprecio_codigo_preciohultdelivery_codigo"),
        (
            "proveedores",
            "0004_rename_codigo_precio_proveedoragregadoprecio_codigo_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="proveedoragregadoprecio",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("proveedor", "agregado"),
                name="unique_proveedor_agregado_activo",
            ),
        ),
        migrations.AddConstraint(
            model_name="proveedortipoconcretoprecio",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("proveedor", "tipo_concreto"),
                name="unique_proveedor_tipo_concreto_activo",
            ),
        ),
    ]
