# Generated by Django 5.0 on 2026-02-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "proveedores",
            "0005_proveedoragregadoprecio_unique_proveedor_agregado_activo_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proveedor",
            name="fecha_actualizacion",
        ),
        migrations.RemoveField(
            model_name="proveedoragregadoprecio",
            name="fecha_actualizacion",
        ),
        migrations.RemoveField(
            model_name="proveedortipoconcretoprecio",
            name="fecha_actualizacion",
        ),
        migrations.AddField(
            model_name="proveedor",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha Modificación"
            ),
        ),
        migrations.AddField(
            model_name="proveedoragregadoprecio",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha Modificación"
            ),
        ),
        migrations.AddField(
            model_name="proveedortipoconcretoprecio",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha Modificación"
            ),
        ),
    ]
