# Generated by Django 6.0.2 on 2026-02-15 18:09

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0006_historicalagregado_historicalagregadoprecio_and_more"),
        ("proveedores", "0006_remove_proveedor_fecha_actualizacion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProveedor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Nombre"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Proveedor",
                "verbose_name_plural": "historical Proveedores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProveedorAgregadoPrecio",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Código"
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "agregado",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="administracion.agregado",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="proveedores.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Precio de Agregado",
                "verbose_name_plural": "historical Precios de Agregados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProveedorTipoConcretoPrecio",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Código"
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="proveedores.proveedor",
                    ),
                ),
                (
                    "tipo_concreto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="administracion.tipoconcreto",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Precio de Tipo Concreto",
                "verbose_name_plural": "historical Precios de Tipos de Concretos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
