# Generated by Django 5.0 on 2025-12-31 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auxiliares", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conductor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "licencia",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Licencia"
                    ),
                ),
                ("telefono", models.CharField(max_length=15, verbose_name="Teléfono")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "estado_conductor_nombre",
                    models.ForeignKey(
                        db_column="estado_conductor",
                        default="disponible",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estado_conductor",
                        to="auxiliares.estadoconductor",
                        to_field="nombre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conductor",
                "verbose_name_plural": "Conductores",
                "db_table": 'sistema"."conductor',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Matrícula"
                    ),
                ),
                ("alias", models.CharField(max_length=50, verbose_name="Alias")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "estado_vehiculo_nombre",
                    models.ForeignKey(
                        db_column="estado_vehiculo",
                        default="disponible",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estado_vehiculo",
                        to="auxiliares.estadovehiculo",
                        to_field="nombre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "db_table": 'sistema"."vehiculo',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_entrega", models.DateField(verbose_name="Fecha Entrega")),
                ("hora_entrega", models.TimeField(verbose_name="Hora Entrega")),
                (
                    "direccion_entrega",
                    models.CharField(max_length=255, verbose_name="Dirección Entrega"),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, null=True, verbose_name="Observación"),
                ),
                (
                    "total_yardas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=10,
                        null=True,
                        verbose_name="Total Yardas",
                    ),
                ),
                (
                    "precio_yarda",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio Yarda",
                    ),
                ),
                (
                    "precio_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio Total",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conductor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sistema.conductor",
                    ),
                ),
                (
                    "estado_pedido",
                    models.ForeignKey(
                        db_column="estado_pedido",
                        default="pendiente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estado_pedido",
                        to="auxiliares.estadopedido",
                        to_field="nombre",
                    ),
                ),
                (
                    "vehiculo",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sistema.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "db_table": 'sistema"."pedido',
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="conductor",
            name="vehiculo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehiculo",
                to="sistema.vehiculo",
            ),
        ),
    ]
