# Generated by Django 5.0 on 2026-01-24 03:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auxiliares", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conductor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "licencia",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Licencia"
                    ),
                ),
                ("telefono", models.CharField(max_length=15, verbose_name="Teléfono")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Es Eliminado"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "estado_conductor_nombre",
                    models.ForeignKey(
                        db_column="estado_conductor",
                        default="disponible",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estado_conductor",
                        to="auxiliares.estadoconductor",
                        to_field="nombre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conductor",
                "verbose_name_plural": "Conductores",
                "db_table": 'sistema"."conductor',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_pedido",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Orden"
                    ),
                ),
                (
                    "cantidad_yardas",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=10,
                        verbose_name="Cantidad de Yardas",
                    ),
                ),
                (
                    "direccion_entrega",
                    models.CharField(max_length=255, verbose_name="Dirección Entrega"),
                ),
                ("fecha_entrega", models.DateField(verbose_name="Fecha Entrega")),
                ("hora_entrega", models.TimeField(verbose_name="Hora Entrega")),
                ("nota", models.TextField(blank=True, null=True, verbose_name="Nota")),
                (
                    "slump",
                    models.IntegerField(blank=True, null=True, verbose_name="Slump"),
                ),
                (
                    "precio_yarda",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio Yarda",
                    ),
                ),
                (
                    "precio_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio Total",
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Es Eliminado"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "agregado",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="auxiliares.agregado",
                        verbose_name="Agregados",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estado_pedido",
                    models.ForeignKey(
                        db_column="estado_pedido",
                        default="pendiente",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estado_pedido",
                        to="auxiliares.estadopedido",
                        to_field="nombre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "db_table": 'sistema"."pedido',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Matrícula"
                    ),
                ),
                ("alias", models.CharField(max_length=50, verbose_name="Alias")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Es Eliminado"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "estado_vehiculo_nombre",
                    models.ForeignKey(
                        db_column="estado_vehiculo",
                        default="disponible",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estado_vehiculo",
                        to="auxiliares.estadovehiculo",
                        to_field="nombre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "db_table": 'sistema"."vehiculo',
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_entrega",
                    models.CharField(max_length=20, verbose_name="Código de Entrega"),
                ),
                ("secuencia", models.IntegerField(verbose_name="Secuencia de Entrega")),
                (
                    "yardas_asignadas",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Yardas Asignadas",
                    ),
                ),
                (
                    "fecha_hora_salida",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha/Hora Salida"
                    ),
                ),
                (
                    "fecha_hora_entrega",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha/Hora Entrega"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("en_camino", "En Camino"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="programado",
                        max_length=20,
                    ),
                ),
                (
                    "entregado",
                    models.BooleanField(default=False, verbose_name="Es Entregado"),
                ),
                ("nota", models.TextField(blank=True, null=True, verbose_name="Nota")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Es Eliminado"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "conductor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sistema.conductor",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sistema.pedido"
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sistema.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega",
                "verbose_name_plural": "Entregas",
                "managed": True,
                "unique_together": {("pedido", "secuencia")},
            },
        ),
    ]
