# Generated by Django 5.0 on 2026-02-11 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0001_initial'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.ForeignKey(db_column='estado_pedido', default='Pendiente', on_delete=django.db.models.deletion.PROTECT, related_name='estado_pedido', to='auxiliares.estadopedido', to_field='nombre'),
        ),
    ]
