# Generated by Django 5.0 on 2026-01-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgregadoPedido",
        ),
    ]
