# Generated by Django 5.0 on 2026-02-14 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0002_agregadoprecio_codigo_preciohultdelivery_codigo"),
        ("sistema", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoAgregado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_aplicado",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio Aplicado"
                    ),
                ),
                (
                    "precio_aplicado_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código Precio",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "agregado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="administracion.agregado",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedido_agregados_detalle",
                        to="sistema.pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio de Agregado",
                "verbose_name_plural": "Precios de Agregados",
                "db_table": 'sistema"."pedido_agregado_precios',
                "managed": True,
                "unique_together": {("pedido", "agregado")},
            },
        ),
    ]
