# Generated by Django 5.0 on 2026-01-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pedido",
            old_name="total_yardas",
            new_name="cantidad_yardas",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="conductor",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="observacion",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="vehiculo",
        ),
        migrations.AddField(
            model_name="conductor",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Es Eliminado"),
        ),
        migrations.AddField(
            model_name="pedido",
            name="codigo_pedido",
            field=models.CharField(
                default=1, max_length=20, verbose_name="Código de Pedido"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Es Eliminado"),
        ),
        migrations.AddField(
            model_name="pedido",
            name="nota",
            field=models.TextField(blank=True, null=True, verbose_name="Nota"),
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Es Eliminado"),
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_entrega",
                    models.CharField(max_length=20, verbose_name="Código de Entrega"),
                ),
                ("secuencia", models.IntegerField(verbose_name="Secuencia de Entrega")),
                (
                    "yardas_asignadas",
                    models.DecimalField(
                        decimal_places=1, max_digits=10, verbose_name="Yardas Asignadas"
                    ),
                ),
                ("fecha_entrega", models.DateField(verbose_name="Fecha Entrega")),
                ("hora_entrega", models.TimeField(verbose_name="Hora Entrega")),
                (
                    "entregado",
                    models.BooleanField(default=False, verbose_name="Es Entregado"),
                ),
                ("nota", models.TextField(blank=True, null=True, verbose_name="Nota")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Es Eliminado"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "conductor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sistema.conductor",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sistema.pedido"
                    ),
                ),
                (
                    "vehiculo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sistema.vehiculo",
                    ),
                ),
            ],
        ),
    ]
