# Generated by Django 5.0 on 2026-02-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0002_pedidoagregado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="precio_por_yarda_aplicado_codigo",
            field=models.CharField(
                blank=True,
                null=True,
                verbose_name="Código de Precio por Yarda Aplicado",
            ),
        ),
    ]
