# Generated by Django 5.0 on 2026-01-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0002_rename_total_yardas_pedido_cantidad_yardas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="codigo_pedido",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Código de Pedido"
            ),
        ),
    ]
