# Generated by Django 5.0 on 2026-01-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0003_alter_pedido_codigo_pedido"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entrega",
            options={
                "managed": True,
                "verbose_name": "Entrega",
                "verbose_name_plural": "Entregas",
            },
        ),
    ]
