# Generated by Django 5.0 on 2026-02-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0003_alter_pedido_precio_por_yarda_aplicado_codigo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="fecha_modificacion",
        ),
        migrations.AddField(
            model_name="pedido",
            name="fecha_actualizacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha Actualización"
            ),
        ),
    ]
