# Generated by Django 5.0 on 2026-01-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0004_alter_entrega_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="cantidad_yardas",
            field=models.DecimalField(
                decimal_places=1, default=1, max_digits=10, verbose_name="Total Yardas"
            ),
            preserve_default=False,
        ),
    ]
