# Generated by Django 5.0 on 2026-02-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0004_remove_pedido_fecha_modificacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="fecha_actualizacion",
        ),
        migrations.AddField(
            model_name="pedido",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha Modificación"
            ),
        ),
    ]
