# Generated by Django 5.0 on 2026-01-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0005_alter_pedido_cantidad_yardas"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="agregados",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Agregados"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="slump",
            field=models.IntegerField(blank=True, null=True, verbose_name="Slump"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cantidad_yardas",
            field=models.DecimalField(
                decimal_places=1, max_digits=10, verbose_name="Cantidad de Yardas"
            ),
        ),
    ]
