# Generated by Django 5.0 on 2026-02-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0005_remove_pedido_fecha_actualizacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conductor",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
    ]
