# Generated by Django 5.0 on 2026-01-17 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0006_pedido_agregados_pedido_slump_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrega",
            name="yardas_asignadas",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="Yardas Asignadas",
            ),
        ),
    ]
