# Generated by Django 6.0.2 on 2026-02-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0006_alter_conductor_is_delete_alter_pedido_is_delete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrega",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
    ]
