# Generated by Django 5.0 on 2026-01-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0007_alter_entrega_yardas_asignadas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrega",
            name="fecha_entrega",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha Entrega"),
        ),
        migrations.AlterField(
            model_name="entrega",
            name="hora_entrega",
            field=models.TimeField(blank=True, null=True, verbose_name="Hora Entrega"),
        ),
    ]
