# Generated by Django 6.0.2 on 2026-02-15 18:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion", "0006_historicalagregado_historicalagregadoprecio_and_more"),
        (
            "auxiliares",
            "0003_historicalestadoconductor_historicalestadopedido_and_more",
        ),
        ("sistema", "0007_alter_entrega_is_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="precio_por_delivery_aplicado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Precio por Minimun Hult Delivery Aplicado",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="precio_por_delivery_aplicado_codigo",
            field=models.CharField(
                blank=True,
                null=True,
                verbose_name="Código de Precio por Minimun Hult Delivery Aplicado",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalConductor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "licencia",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Licencia"
                    ),
                ),
                ("telefono", models.CharField(max_length=15, verbose_name="Teléfono")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "estado_conductor_nombre",
                    models.ForeignKey(
                        blank=True,
                        db_column="estado_conductor",
                        db_constraint=False,
                        default="disponible",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auxiliares.estadoconductor",
                        to_field="nombre",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Conductor",
                "verbose_name_plural": "historical Conductores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPedido",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                (
                    "codigo_pedido",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Número de Orden"
                    ),
                ),
                (
                    "cantidad_yardas",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=10,
                        verbose_name="Cantidad de Yardas",
                    ),
                ),
                (
                    "direccion_entrega",
                    models.CharField(max_length=255, verbose_name="Dirección Entrega"),
                ),
                ("fecha_entrega", models.DateField(verbose_name="Fecha Entrega")),
                ("hora_entrega", models.TimeField(verbose_name="Hora Entrega")),
                ("nota", models.TextField(blank=True, null=True, verbose_name="Nota")),
                (
                    "slump",
                    models.IntegerField(blank=True, null=True, verbose_name="Slump"),
                ),
                (
                    "precio_por_yarda_aplicado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio por Yarda Aplicado",
                    ),
                ),
                (
                    "precio_por_yarda_aplicado_codigo",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Código de Precio por Yarda Aplicado",
                    ),
                ),
                (
                    "precio_por_delivery_aplicado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio por Minimun Hult Delivery Aplicado",
                    ),
                ),
                (
                    "precio_por_delivery_aplicado_codigo",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Código de Precio por Minimun Hult Delivery Aplicado",
                    ),
                ),
                (
                    "subtotal_yardas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Subtotal Yardas",
                    ),
                ),
                (
                    "subtotal_agregados",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Subtotal Agregados",
                    ),
                ),
                (
                    "subtotal_hultdelivery",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Subtotal Hultdelivery",
                    ),
                ),
                (
                    "precio_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio Total",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estado_pedido",
                    models.ForeignKey(
                        blank=True,
                        db_column="estado_pedido",
                        db_constraint=False,
                        default="Pendiente",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auxiliares.estadopedido",
                        to_field="nombre",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hultdelivery",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="administracion.hultdelivery",
                    ),
                ),
                (
                    "tipo_concreto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="administracion.tipoconcreto",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Pedido",
                "verbose_name_plural": "historical Pedidos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPedidoAgregado",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "precio_aplicado",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio Aplicado"
                    ),
                ),
                (
                    "precio_aplicado_codigo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Código Precio",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Creación"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "agregado",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="administracion.agregado",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sistema.pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Precio de Agregado",
                "verbose_name_plural": "historical Precios de Agregados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVehiculo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha Modificación"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                (
                    "matricula",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Matrícula"
                    ),
                ),
                ("alias", models.CharField(max_length=50, verbose_name="Alias")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "estado_vehiculo_nombre",
                    models.ForeignKey(
                        blank=True,
                        db_column="estado_vehiculo",
                        db_constraint=False,
                        default="disponible",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="auxiliares.estadovehiculo",
                        to_field="nombre",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Vehículo",
                "verbose_name_plural": "historical Vehículos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
