# Generated by Django 5.0 on 2026-01-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistema", "0008_alter_entrega_fecha_entrega_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="entrega",
            unique_together={("pedido", "secuencia")},
        ),
        migrations.AddField(
            model_name="entrega",
            name="estado",
            field=models.CharField(
                choices=[
                    ("programado", "Programado"),
                    ("en_camino", "En Camino"),
                    ("entregado", "Entregado"),
                    ("cancelado", "Cancelado"),
                ],
                default="programado",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="entrega",
            name="fecha_hora_entrega",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha/Hora Entrega"
            ),
        ),
        migrations.AddField(
            model_name="entrega",
            name="fecha_hora_salida",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha/Hora Salida"
            ),
        ),
        migrations.AlterField(
            model_name="entrega",
            name="conductor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="sistema.conductor"
            ),
        ),
        migrations.AlterField(
            model_name="entrega",
            name="vehiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="sistema.vehiculo"
            ),
        ),
        migrations.RemoveField(
            model_name="entrega",
            name="fecha_entrega",
        ),
        migrations.RemoveField(
            model_name="entrega",
            name="hora_entrega",
        ),
    ]
