# Generated by Django 5.0 on 2026-01-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_alter_entrega_unique_together_entrega_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='vehiculo',
        ),
    ]
