# Generated by Django 5.0 on 2026-01-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_remove_conductor_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_viaje', 'En Viaje'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='programado', max_length=20),
        ),
    ]
