# Generated by Django 5.0 on 2026-01-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_alter_entrega_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_camino', 'En Camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='programado', max_length=20),
        ),
    ]
